"use strict";

/** VVC Smart Document Scanner. Confirmed scans use IndexedDB; transient frames stay in memory. */
const SCANNER_DB = "vvcSmartDocumentsV1";
const SCANNER_STORE = "documents";
const OPENCV_URL = "https://docs.opencv.org/4.x/opencv.js";
const JSPDF_URL = "https://cdn.jsdelivr.net/npm/jspdf@4.2.1/dist/jspdf.umd.min.js";
const scannerState = { stream:null, loop:null, cv:null, cvFailed:false, stableFrames:0, lastQuad:null, lastQuality:null, countdown:false, torch:false, pages:[], replacePageId:null, sourceImage:null, rotation:0, generated:null, generatedUrl:null };
const scannerEl = (id) => document.getElementById(id);
const scannerClean = (value,max=120) => String(value||"").replace(/[\u0000-\u001F<>]/g,"").trim().slice(0,max);

function openScannerDb(){return new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error("IndexedDB is unavailable."));return;}const request=indexedDB.open(SCANNER_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(SCANNER_STORE))db.createObjectStore(SCANNER_STORE,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function scannerDbPut(value){const db=await openScannerDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SCANNER_STORE,"readwrite");tx.objectStore(SCANNER_STORE).put(value);tx.oncomplete=()=>{db.close();resolve(value);};tx.onerror=()=>{db.close();reject(tx.error);};});}
async function scannerDbGet(id){if(!id)return null;const db=await openScannerDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SCANNER_STORE,"readonly");const request=tx.objectStore(SCANNER_STORE).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();});}

function loadExternalScript(src,test){if(test())return Promise.resolve();return new Promise((resolve,reject)=>{const existing=document.querySelector(`script[src="${src}"]`);if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",reject,{once:true});return;}const script=document.createElement("script");script.src=src;script.async=true;script.crossOrigin="anonymous";script.onload=resolve;script.onerror=()=>reject(new Error(`Unable to load ${src}`));document.head.append(script);});}
async function loadOpenCv(){if(scannerState.cv)return scannerState.cv;if(scannerState.cvFailed)throw new Error("Automatic edge detection is unavailable.");try{await loadExternalScript(OPENCV_URL,()=>Boolean(window.cv));let cv=window.cv;if(cv instanceof Promise)cv=await cv;const started=Date.now();while(!cv?.Mat&&Date.now()-started<12000)await new Promise((r)=>setTimeout(r,100));if(!cv?.Mat)throw new Error("OpenCV did not initialize.");scannerState.cv=cv;return cv;}catch(error){scannerState.cvFailed=true;throw error;}}
async function loadJsPdf(){await loadExternalScript(JSPDF_URL,()=>Boolean(window.jspdf?.jsPDF));if(!window.jspdf?.jsPDF)throw new Error("PDF generator failed to load.");return window.jspdf.jsPDF;}

function showScannerStage(id){["scannerStartStage","scannerCameraStage","scannerEditorStage","scannerPagesStage"].forEach((stage)=>{const node=scannerEl(stage);if(node)node.hidden=stage!==id;});}
function openScanner(){const modal=scannerEl("documentScannerModal");if(!modal)return;modal.classList.add("active");document.body.classList.add("modal-open");showScannerStage(scannerState.pages.length?"scannerPagesStage":"scannerStartStage");renderScannerPages();}
function revokeScannerUrls(){scannerState.pages.forEach((page)=>{if(page.url)URL.revokeObjectURL(page.url);page.url="";});if(scannerState.generatedUrl){URL.revokeObjectURL(scannerState.generatedUrl);scannerState.generatedUrl=null;}}
function stopCamera(){if(scannerState.loop){clearInterval(scannerState.loop);scannerState.loop=null;}if(scannerState.stream){scannerState.stream.getTracks().forEach((track)=>track.stop());scannerState.stream=null;}const video=scannerEl("scannerVideo");if(video)video.srcObject=null;scannerState.countdown=false;scannerState.stableFrames=0;scannerState.lastQuad=null;}
function closeScanner(){stopCamera();revokeScannerUrls();scannerState.pages=[];scannerState.generated=null;scannerState.sourceImage=null;scannerEl("documentScannerModal")?.classList.remove("active");if(!document.querySelector(".modal.active"))document.body.classList.remove("modal-open");}
function statusNode(id,text,state=""){const node=scannerEl(id);if(!node)return;node.textContent=text;node.className=state;}

async function startCamera(){const fallback=scannerEl("scannerFallbackMessage");fallback.textContent="";if(!navigator.mediaDevices?.getUserMedia){fallback.textContent="Camera scanning is unsupported. Choose existing images instead.";return;}showScannerStage("scannerCameraStage");statusNode("cameraStatus","Requesting camera permission…","warning");try{scannerState.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});const video=scannerEl("scannerVideo");video.srcObject=scannerState.stream;await video.play();statusNode("cameraStatus","Camera ready","good");setupTorch();startDetectionLoop();loadOpenCv().then(()=>statusNode("edgeStatus","Edge detection ready","good")).catch(()=>{statusNode("edgeStatus","Manual capture mode","warning");fallback.textContent="Automatic detection could not load. Manual capture remains available.";});}catch(error){stopCamera();showScannerStage("scannerStartStage");fallback.textContent=error.name==="NotAllowedError"?"Camera permission was denied. Allow camera access or choose images from Files/Photos.":"No usable camera was found. Choose existing images instead.";}}
function setupTorch(){const track=scannerState.stream?.getVideoTracks()[0];const capabilities=track?.getCapabilities?.()||{};const button=scannerEl("toggleTorch");button.disabled=!capabilities.torch;button.textContent=capabilities.torch?"Turn flash on":"Flash unavailable";}
async function toggleTorch(){const track=scannerState.stream?.getVideoTracks()[0];if(!track?.getCapabilities?.().torch)return;scannerState.torch=!scannerState.torch;try{await track.applyConstraints({advanced:[{torch:scannerState.torch}]});scannerEl("toggleTorch").textContent=scannerState.torch?"Turn flash off":"Turn flash on";}catch{scannerEl("toggleTorch").disabled=true;scannerEl("toggleTorch").textContent="Flash unavailable";}}

function orderQuad(points){const sum=(p)=>p.x+p.y,diff=(p)=>p.y-p.x;return [points.reduce((a,b)=>sum(a)<sum(b)?a:b),points.reduce((a,b)=>diff(a)<diff(b)?a:b),points.reduce((a,b)=>sum(a)>sum(b)?a:b),points.reduce((a,b)=>diff(a)>diff(b)?a:b)];}
function quadDistance(a,b){if(!a||!b)return Infinity;return a.reduce((total,p,index)=>total+Math.hypot(p.x-b[index].x,p.y-b[index].y),0)/4;}
function drawQuad(quad,width,height){const overlay=scannerEl("scannerDetectionOverlay"),video=scannerEl("scannerVideo");overlay.width=video.clientWidth*devicePixelRatio;overlay.height=video.clientHeight*devicePixelRatio;const ctx=overlay.getContext("2d");ctx.clearRect(0,0,overlay.width,overlay.height);if(!quad)return;const sx=overlay.width/width,sy=overlay.height/height;ctx.strokeStyle="#ffd34e";ctx.lineWidth=4*devicePixelRatio;ctx.fillStyle="rgba(255,211,78,.08)";ctx.beginPath();quad.forEach((p,i)=>i?ctx.lineTo(p.x*sx,p.y*sy):ctx.moveTo(p.x*sx,p.y*sy));ctx.closePath();ctx.fill();ctx.stroke();}
function detectDocument(){const video=scannerEl("scannerVideo");if(!video?.videoWidth||!scannerState.cv)return;const canvas=scannerEl("scannerAnalysisCanvas"),width=640,height=Math.round(640*video.videoHeight/video.videoWidth);canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(video,0,0,width,height);const cv=scannerState.cv;let src,gray,blurred,edges,contours,hierarchy,lap;try{src=cv.imread(canvas);gray=new cv.Mat();blurred=new cv.Mat();edges=new cv.Mat();contours=new cv.MatVector();hierarchy=new cv.Mat();lap=new cv.Mat();cv.cvtColor(src,gray,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(gray,blurred,new cv.Size(5,5),0);cv.Canny(blurred,edges,60,170);cv.findContours(edges,contours,hierarchy,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE);let best=null,bestArea=0;for(let i=0;i<contours.size();i++){const contour=contours.get(i),peri=cv.arcLength(contour,true),approx=new cv.Mat();cv.approxPolyDP(contour,approx,.02*peri,true);const area=Math.abs(cv.contourArea(approx));if(approx.rows===4&&area>bestArea){bestArea=area;best=Array.from({length:4},(_,j)=>({x:approx.intPtr(j,0)[0],y:approx.intPtr(j,0)[1]}));}approx.delete();contour.delete();}cv.Laplacian(gray,lap,cv.CV_64F);const mean=new cv.Mat(),std=new cv.Mat();cv.meanStdDev(lap,mean,std);const blurScore=std.doubleAt(0,0)**2;const light=cv.mean(gray)[0];mean.delete();std.delete();const ordered=best?orderQuad(best):null,fill=bestArea/(width*height),stable=quadDistance(scannerState.lastQuad,ordered)<9;scannerState.lastQuad=ordered;scannerState.lastQuality={good:Boolean(ordered&&fill>.28&&stable&&blurScore>75&&light>50&&light<220),fill,stable,blurScore,light,width,height};drawQuad(ordered,width,height);statusNode("edgeStatus",ordered?"Four edges detected":"Position all four edges",ordered?"good":"warning");statusNode("lightingStatus",light<50?"More light needed":light>220?"Too much glare":"Lighting good",light>50&&light<220?"good":"warning");statusNode("stabilityStatus",stable?"Document stable":"Hold device steady",stable?"good":"warning");scannerState.stableFrames=scannerState.lastQuality.good?scannerState.stableFrames+1:0;if(scannerState.stableFrames>=5&&scannerEl("autoCaptureToggle").checked&&!scannerState.countdown)autoCaptureCountdown();}catch{scannerState.cvFailed=true;statusNode("edgeStatus","Manual capture mode","warning");}finally{[src,gray,blurred,edges,contours,hierarchy,lap].forEach((mat)=>mat?.delete?.());}}
function startDetectionLoop(){if(scannerState.loop)clearInterval(scannerState.loop);scannerState.loop=setInterval(detectDocument,320);}
async function autoCaptureCountdown(){scannerState.countdown=true;const node=scannerEl("captureCountdown");node.hidden=false;for(let count=3;count>0;count--){if(!scannerState.lastQuality?.good||!scannerEl("autoCaptureToggle").checked){node.hidden=true;scannerState.countdown=false;return;}node.textContent=String(count);await new Promise((r)=>setTimeout(r,650));}node.hidden=true;await captureFrame(true);scannerState.countdown=false;}

async function canvasToImage(canvas){const image=new Image();const url=canvas.toDataURL("image/jpeg",.96);await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});return image;}
async function captureFrame(automatic=false){const video=scannerEl("scannerVideo");if(!video?.videoWidth)return;const raw=document.createElement("canvas");raw.width=video.videoWidth;raw.height=video.videoHeight;raw.getContext("2d").drawImage(video,0,0);let result=raw;if(scannerState.lastQuad&&scannerState.cv&&!scannerState.cvFailed){try{result=perspectiveCrop(raw,scannerState.lastQuad,scannerState.lastQuality.width,scannerState.lastQuality.height);}catch{result=raw;}}const flash=scannerEl("captureFlash");flash.hidden=false;setTimeout(()=>{flash.hidden=true;},120);stopCamera();scannerState.sourceImage=await canvasToImage(result);resetEditorControls();renderEditor();showScannerStage("scannerEditorStage");if(automatic)statusNode("cameraStatus","Auto-captured","good");}
function perspectiveCrop(canvas,quad,analysisWidth,analysisHeight){const cv=scannerState.cv,src=cv.imread(canvas),scaled=quad.map((p)=>({x:p.x*canvas.width/analysisWidth,y:p.y*canvas.height/analysisHeight}));const [tl,tr,br,bl]=scaled;const width=Math.max(Math.hypot(br.x-bl.x,br.y-bl.y),Math.hypot(tr.x-tl.x,tr.y-tl.y));const height=Math.max(Math.hypot(tr.x-br.x,tr.y-br.y),Math.hypot(tl.x-bl.x,tl.y-bl.y));const srcPts=cv.matFromArray(4,1,cv.CV_32FC2,[tl.x,tl.y,tr.x,tr.y,br.x,br.y,bl.x,bl.y]);const dstPts=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,width,0,width,height,0,height]);const transform=cv.getPerspectiveTransform(srcPts,dstPts),dst=new cv.Mat();cv.warpPerspective(src,dst,transform,new cv.Size(Math.round(width),Math.round(height)),cv.INTER_LINEAR,cv.BORDER_CONSTANT,new cv.Scalar());const output=document.createElement("canvas");output.width=dst.cols;output.height=dst.rows;cv.imshow(output,dst);[src,srcPts,dstPts,transform,dst].forEach((mat)=>mat.delete());return output;}

function resetEditorControls(){scannerState.rotation=0;["scanBrightness","scanContrast"].forEach((id)=>scannerEl(id).value=100);scannerEl("scanColourMode").value="colour";scannerEl("scanSharpen").checked=false;scannerEl("cropLeft").value=0;scannerEl("cropTop").value=0;scannerEl("cropRight").value=100;scannerEl("cropBottom").value=100;}
function renderEditor(){const image=scannerState.sourceImage,canvas=scannerEl("scannerEditCanvas");if(!image||!canvas)return;const left=+scannerEl("cropLeft").value/100,top=+scannerEl("cropTop").value/100,right=+scannerEl("cropRight").value/100,bottom=+scannerEl("cropBottom").value/100;const sw=Math.max(20,image.naturalWidth*(right-left)),sh=Math.max(20,image.naturalHeight*(bottom-top)),rotated=Math.abs(scannerState.rotation)%180===90;const max=2200,scale=Math.min(1,max/(rotated?sh:sw),max/(rotated?sw:sh));canvas.width=Math.round((rotated?sh:sw)*scale);canvas.height=Math.round((rotated?sw:sh)*scale);const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(scannerState.rotation*Math.PI/180);const brightness=+scannerEl("scanBrightness").value,contrast=+scannerEl("scanContrast").value,mode=scannerEl("scanColourMode").value;ctx.filter=`brightness(${brightness}%) contrast(${contrast}%)${mode==="grayscale"?" grayscale(100%)":""}`;ctx.drawImage(image,image.naturalWidth*left,image.naturalHeight*top,sw,sh,-sw*scale/2,-sh*scale/2,sw*scale,sh*scale);ctx.restore();if(mode==="bw"||scannerEl("scanSharpen").checked)postProcessCanvas(canvas,mode==="bw",scannerEl("scanSharpen").checked);scannerEl("brightnessValue").textContent=`${brightness}%`;scannerEl("contrastValue").textContent=`${contrast}%`;}
function postProcessCanvas(canvas,bw,sharpen){const ctx=canvas.getContext("2d",{willReadFrequently:true}),image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data;if(bw){for(let i=0;i<data.length;i+=4){const gray=.299*data[i]+.587*data[i+1]+.114*data[i+2],value=gray>155?255:0;data[i]=data[i+1]=data[i+2]=value;}ctx.putImageData(image,0,0);}if(sharpen&&canvas.width*canvas.height<6000000){const source=new Uint8ClampedArray(data),w=canvas.width,h=canvas.height;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=(y*w+x)*4;for(let c=0;c<3;c++)data[p+c]=Math.max(0,Math.min(255,5*source[p+c]-source[p-4+c]-source[p+4+c]-source[p-w*4+c]-source[p+w*4+c]));}ctx.putImageData(image,0,0);}}
function canvasBlob(canvas,type="image/jpeg",quality=.9){return new Promise((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("Image processing failed.")),type,quality));}
async function confirmPage(){renderEditor();const blob=await canvasBlob(scannerEl("scannerEditCanvas"));const page={id:scannerState.replacePageId||`page-${Date.now()}-${Math.random().toString(16).slice(2)}`,blob,url:URL.createObjectURL(blob)};const index=scannerState.pages.findIndex((item)=>item.id===scannerState.replacePageId);if(index>=0){if(scannerState.pages[index].url)URL.revokeObjectURL(scannerState.pages[index].url);scannerState.pages[index]=page;}else scannerState.pages.push(page);scannerState.replacePageId=null;scannerState.sourceImage=null;renderScannerPages();showScannerStage("scannerPagesStage");}
async function addFiles(files){for(const file of [...files]){if(!file.type.startsWith("image/"))continue;const url=URL.createObjectURL(file);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const canvas=document.createElement("canvas"),scale=Math.min(1,2200/image.naturalWidth,2200/image.naturalHeight);canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const blob=await canvasBlob(canvas);scannerState.pages.push({id:`page-${Date.now()}-${Math.random().toString(16).slice(2)}`,blob,url:URL.createObjectURL(blob)});}finally{URL.revokeObjectURL(url);}}renderScannerPages();showScannerStage("scannerPagesStage");}
function renderScannerPages(){const list=scannerEl("scannerPageList");if(!list)return;list.replaceChildren();scannerState.pages.forEach((page,index)=>{if(!page.url)page.url=URL.createObjectURL(page.blob);const card=document.createElement("article");card.className="scanner-page-card";const img=document.createElement("img");img.src=page.url;img.alt=`Scanned page ${index+1}`;const title=document.createElement("strong");title.textContent=`Page ${index+1}`;const actions=document.createElement("div");actions.className="scanner-page-actions";[["↑","up"],["↓","down"],["Rescan","rescan"],["Delete","delete"]].forEach(([label,action])=>{const button=document.createElement("button");button.type="button";button.textContent=label;button.dataset.pageAction=action;button.dataset.pageId=page.id;button.setAttribute("aria-label",`${label} page ${index+1}`);actions.append(button);});card.append(img,title,actions);list.append(card);});const bytes=scannerState.pages.reduce((sum,page)=>sum+page.blob.size,0);scannerEl("scannerPageStats").textContent=`${scannerState.pages.length} confirmed page${scannerState.pages.length===1?"":"s"}`;scannerEl("scanPageCount").textContent=`${scannerState.pages.length} page${scannerState.pages.length===1?"":"s"}`;scannerEl("scanSizeEstimate").textContent=`Estimated PDF size: ${Math.max(1,Math.round(bytes*.78/1024))} KB`;}

function blobDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}
async function generatePdf(){if(!scannerState.pages.length){alert("Add at least one confirmed page.");return;}const title=scannerClean(scannerEl("scanDocumentTitle").value,120),category=scannerClean(scannerEl("scanDocumentCategory").value,80),date=scannerClean(scannerEl("scanDocumentDate").value,10);let filename=scannerClean(scannerEl("scanPdfFilename").value,80).replace(/[^a-zA-Z0-9._-]+/g,"-");if(!filename.toLowerCase().endsWith(".pdf"))filename+=".pdf";if(!title){alert("Enter a document title.");return;}const button=scannerEl("generateScanPdf");button.disabled=true;button.textContent="Generating PDF…";try{const jsPDF=await loadJsPdf(),pdf=new jsPDF({orientation:"portrait",unit:"mm",format:"a4",compress:true});for(let index=0;index<scannerState.pages.length;index++){if(index)pdf.addPage();const data=await blobDataUrl(scannerState.pages[index].blob),properties=pdf.getImageProperties(data),ratio=Math.min(190/properties.width,277/properties.height),w=properties.width*ratio,h=properties.height*ratio;pdf.addImage(data,"JPEG",(210-w)/2,(297-h)/2,w,h,undefined,"MEDIUM");}const blob=pdf.output("blob"),id=`scan-${Date.now()}-${Math.random().toString(16).slice(2)}`,record={id,title,category,date,filename,pageCount:scannerState.pages.length,size:blob.size,pdfBlob:blob,pages:scannerState.pages.map((page)=>page.blob),createdAt:new Date().toISOString()};await scannerDbPut(record);if(scannerState.generatedUrl)URL.revokeObjectURL(scannerState.generatedUrl);scannerState.generated=record;scannerState.generatedUrl=URL.createObjectURL(blob);scannerEl("scannerPdfResult").hidden=false;scannerEl("scannerPdfResultTitle").textContent=title;scannerEl("scannerPdfResultMeta").textContent=`${record.pageCount} pages · ${Math.round(blob.size/1024)} KB · ${category}`;}catch(error){alert(`PDF generation failed: ${error.message}. You can keep the confirmed pages and try again when the library is available.`);}finally{button.disabled=false;button.textContent="Generate optimized PDF";}}

async function openDocument(id,action="view"){try{const record=await scannerDbGet(id);if(!record)throw new Error("This document is not available on this device.");const url=URL.createObjectURL(record.pdfBlob);if(action==="download"){const link=document.createElement("a");link.href=url;link.download=record.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}if(action==="print"){const frame=scannerEl("scannerPdfFrame");showDocumentViewer(record,url);frame.addEventListener("load",()=>{try{frame.contentWindow.print();}catch{}},{once:true});return;}showDocumentViewer(record,url);}catch(error){alert(error.message);}}
function showDocumentViewer(record,url){const viewer=scannerEl("scannerDocumentViewer"),frame=scannerEl("scannerPdfFrame");if(!viewer||!frame){URL.revokeObjectURL(url);return;}if(frame.dataset.objectUrl)URL.revokeObjectURL(frame.dataset.objectUrl);frame.src=url;frame.dataset.objectUrl=url;scannerEl("scannerViewerTitle").textContent=record.title;viewer.classList.add("active");document.body.classList.add("modal-open");}
function closeDocumentViewer(){const viewer=scannerEl("scannerDocumentViewer"),frame=scannerEl("scannerPdfFrame");if(frame?.dataset.objectUrl){URL.revokeObjectURL(frame.dataset.objectUrl);delete frame.dataset.objectUrl;}if(frame)frame.src="about:blank";viewer?.classList.remove("active");if(!document.querySelector(".modal.active"))document.body.classList.remove("modal-open");}

function attachGenerated(){const record=scannerState.generated;if(!record)return;scannerEl("scannedDocumentId").value=record.id;const summary=scannerEl("attachedScanSummary");summary.hidden=false;summary.textContent=`Attached: ${record.title} · ${record.pageCount} pages · ${Math.round(record.size/1024)} KB`;closeScanner();}

document.addEventListener("click",async(event)=>{if(event.target.closest("#openDocumentScanner")){openScanner();return;}if(event.target.closest("#closeDocumentScanner,[data-close-scanner]")){closeScanner();return;}if(event.target.closest("#startScannerCamera,#addCameraPage")){await startCamera();return;}if(event.target.closest("#stopScannerCamera")){stopCamera();showScannerStage(scannerState.pages.length?"scannerPagesStage":"scannerStartStage");return;}if(event.target.closest("#toggleTorch")){await toggleTorch();return;}if(event.target.closest("#manualCapture")){await captureFrame(false);return;}if(event.target.closest("#rotateScanLeft")){scannerState.rotation=(scannerState.rotation-90)%360;renderEditor();return;}if(event.target.closest("#rotateScanRight")){scannerState.rotation=(scannerState.rotation+90)%360;renderEditor();return;}if(event.target.closest("#retakeScan")){scannerState.sourceImage=null;await startCamera();return;}if(event.target.closest("#confirmScanPage")){await confirmPage();return;}if(event.target.closest("#generateScanPdf")){await generatePdf();return;}if(event.target.closest("#previewScannedPages")){if(scannerState.pages[0]){scannerState.replacePageId=scannerState.pages[0].id;scannerState.sourceImage=await canvasToImage(await blobToCanvas(scannerState.pages[0].blob));resetEditorControls();renderEditor();showScannerStage("scannerEditorStage");}return;}if(event.target.closest("#previewGeneratedPdf")){if(scannerState.generated)openDocument(scannerState.generated.id);return;}if(event.target.closest("#downloadGeneratedPdf")){if(scannerState.generated)openDocument(scannerState.generated.id,"download");return;}if(event.target.closest("#attachGeneratedPdf")){attachGenerated();return;}if(event.target.closest("#closeScannerViewer,[data-close-document-viewer]")){closeDocumentViewer();return;}const pageButton=event.target.closest("[data-page-action]");if(pageButton){const index=scannerState.pages.findIndex((page)=>page.id===pageButton.dataset.pageId),action=pageButton.dataset.pageAction;if(index<0)return;if(action==="delete"){if(scannerState.pages[index].url)URL.revokeObjectURL(scannerState.pages[index].url);scannerState.pages.splice(index,1);}if(action==="up"&&index>0)[scannerState.pages[index-1],scannerState.pages[index]]=[scannerState.pages[index],scannerState.pages[index-1]];if(action==="down"&&index<scannerState.pages.length-1)[scannerState.pages[index+1],scannerState.pages[index]]=[scannerState.pages[index],scannerState.pages[index+1]];if(action==="rescan"){scannerState.replacePageId=scannerState.pages[index].id;await startCamera();return;}renderScannerPages();return;}const docButton=event.target.closest("[data-scanned-document]");if(docButton){await openDocument(docButton.dataset.scannedDocument,docButton.dataset.documentAction||"view");}});

async function blobToCanvas(blob){const url=URL.createObjectURL(blob);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext("2d").drawImage(image,0,0);return canvas;}finally{URL.revokeObjectURL(url);}}
["scannerFileInput","scannerAddFiles"].forEach((id)=>scannerEl(id)?.addEventListener("change",async(event)=>{await addFiles(event.target.files);event.target.value="";}));
["scanBrightness","scanContrast","scanColourMode","scanSharpen","cropLeft","cropTop","cropRight","cropBottom"].forEach((id)=>scannerEl(id)?.addEventListener("input",renderEditor));
document.addEventListener("keydown",(event)=>{if(event.key==="Escape"){if(scannerEl("scannerDocumentViewer")?.classList.contains("active"))closeDocumentViewer();else if(scannerEl("documentScannerModal")?.classList.contains("active"))closeScanner();}if((event.key==="Enter"||event.key===" ")&&document.activeElement?.id==="manualCapture"){event.preventDefault();captureFrame(false);}});
window.addEventListener("pagehide",()=>{stopCamera();closeDocumentViewer();});

window.VVCDocuments={get:scannerDbGet,open:openDocument};
